# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-03-29T16:24:27+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field, conint


class JobStatus(Enum):
    pending = 'pending'
    running = 'running'
    waiting = 'waiting'
    error = 'error'
    done = 'done'


class ErrorResponse(BaseModel):
    error: str = Field(..., description='Human-readable error message.')


class OkResponse(BaseModel):
    ok: bool = Field(..., description='Always true on success.')


class StageSummary(BaseModel):
    name: str = Field(..., description='Stage identifier (e.g. `ocr`, `clarify`).')
    type: str = Field(..., description='Stage handler type (e.g. `llm_text`, `embed`).')
    model: str | None = Field(None, description='Model used by this stage.')


class Output(BaseModel):
    field: str = Field(..., description='Output field name.')
    type: str = Field(..., description='Output type (e.g. `text`, `json_array`).')


class StageDetail(StageSummary):
    inputs: list[str] | None = Field(
        None, description='Field names consumed by this stage.'
    )
    outputs: list[Output] | None = Field(
        None, description='Fields produced by this stage.'
    )
    skip_if: dict[str, Any] | None = Field(
        None, description='Conditions under which this stage is skipped entirely.'
    )
    start_if: dict[str, Any] | None = Field(
        None, description='Conditions that must be met before this stage can start.'
    )
    continue_if: list[dict[str, Any]] | None = Field(
        None,
        description='Rules that determine if the stage auto-advances without human review.',
    )


class Pipeline(BaseModel):
    id: str = Field(..., description='Pipeline identifier (filename stem).')
    name: str = Field(..., description='Human-readable pipeline name.')
    stages: list[StageSummary] = Field(
        ..., description='Ordered list of stage summaries.'
    )


class PipelineDetail(BaseModel):
    id: str = Field(..., description='Pipeline identifier (filename stem).')
    name: str = Field(..., description='Human-readable pipeline name.')
    stages: list[StageDetail] = Field(..., description='Ordered list of stage details.')


class PaginatedPipelines(BaseModel):
    data: list[Pipeline]
    next_page_token: str | None = Field(
        None,
        description='Opaque cursor; pass as `page_token` on next request. Null when no more pages.',
    )


class Artifact(BaseModel):
    id: UUID = Field(..., description='Unique artifact identifier.')
    filename: str = Field(..., description='Original filename of the artifact.')
    content_type: str = Field(
        ..., description='MIME type (e.g. `image/png`, `text/plain`).'
    )
    created_job_id: UUID | None = Field(
        None,
        description='UUID of the job that created this artifact. Null for source artifacts created during ingest.',
    )
    created_at: datetime = Field(..., description='ISO 8601 creation timestamp.')
    updated_at: datetime = Field(..., description='ISO 8601 last-updated timestamp.')


class DocumentSummary(BaseModel):
    id: UUID = Field(..., description='Unique document identifier.')
    title: str | None = Field(None, description='Human-readable title.')
    current_job_id: UUID | None = Field(
        None, description='UUID of the most recently active job for this document.'
    )
    created_at: datetime = Field(..., description='ISO 8601 creation timestamp.')
    updated_at: datetime = Field(..., description='ISO 8601 last-updated timestamp.')


class DocumentDetail(DocumentSummary):
    additional_context: str | None = Field(
        None, description='Free-text context attached by the user to guide LLM stages.'
    )
    linked_contexts: list[UUID] | None = Field(
        None, description='UUIDs of saved context entries linked to this document.'
    )
    artifacts: list[Artifact] | None = Field(
        None, description='Files associated with this document (e.g. source image).'
    )


class PaginatedDocuments(BaseModel):
    data: list[DocumentSummary]
    next_page_token: str | None = Field(
        None,
        description='Opaque cursor; pass as `page_token` on next request. Null when no more pages.',
    )


class PatchDocumentBody(BaseModel):
    title: str | None = Field(
        None, description='Updated document title. Null clears the title.'
    )
    additional_context: str | None = Field(
        None, description='Free-text context to attach to the document. Null clears it.'
    )
    linked_contexts: list[UUID] | None = Field(
        None,
        description='UUIDs of context entries to link. Null clears all linked contexts.',
    )


class RunIOField(BaseModel):
    field: str | None = Field(
        None, description='Field name (e.g. `ocr_raw`, `clarified_text`).'
    )
    text: str = Field(..., description='Field value.')


class RunQuestion(BaseModel):
    segment: str = Field(
        ..., description='The text segment that prompted the question.'
    )
    question: str = Field(
        ..., description='The clarification question to present to the user.'
    )
    answer: str | None = Field(
        None, description="The user's answer. Null until answered."
    )


class RunSuggestions(BaseModel):
    additional_context: str | None = Field(
        None, description="Suggested update to the document's additional context."
    )
    linked_context: str | None = Field(
        None, description='Suggested update to the linked context entry text.'
    )
    linked_context_id: UUID | None = Field(
        None, description='UUID of the linked context entry this suggestion applies to.'
    )


class Confidence(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class Run(BaseModel):
    id: UUID = Field(..., description='Unique run identifier.')
    inputs: list[RunIOField] = Field(..., description='Fields fed into the LLM.')
    outputs: list[RunIOField] = Field(..., description='Fields produced by the LLM.')
    confidence: Confidence = Field(
        ..., description='LLM-reported confidence in the output.'
    )
    questions: list[RunQuestion] = Field(
        ..., description='Clarification questions raised by the LLM.'
    )
    suggestions: RunSuggestions
    created_at: datetime = Field(
        ..., description='ISO 8601 timestamp when this run started.'
    )
    updated_at: datetime = Field(
        ..., description='ISO 8601 timestamp when this run was last updated.'
    )


class EmbedOptions(BaseModel):
    embed_image: bool | None = Field(
        False,
        description='Whether to include a visual image vector in addition to the text vector.',
    )


class JobOptions(BaseModel):
    require_context: bool | None = Field(
        False, description='Whether this stage requires context before it can run.'
    )
    embed: EmbedOptions | None = None


class JobSummary(BaseModel):
    id: UUID = Field(..., description='Unique job identifier.')
    document_id: UUID = Field(
        ..., description='UUID of the document this job belongs to.'
    )
    title: str | None = Field(None, description='Denormalized document title.')
    stage: str = Field(
        ..., description='Pipeline stage this job executes (e.g. `ocr`, `clarify`).'
    )
    status: JobStatus
    created_at: datetime = Field(..., description='ISO 8601 creation timestamp.')
    updated_at: datetime = Field(..., description='ISO 8601 last-updated timestamp.')


class JobDetail(JobSummary):
    options: JobOptions | None = None
    runs: list[Run] | None = Field(
        None,
        description='Ordered list of LLM round trips for this job. Appended on each execution.',
    )


class PaginatedJobs(BaseModel):
    data: list[JobSummary]
    next_page_token: str | None = Field(
        None,
        description='Opaque cursor; pass as `page_token` on next request. Null when no more pages.',
    )


class Status(Enum):
    pending = 'pending'
    done = 'done'
    error = 'error'


class PutJobStatusBody(BaseModel):
    status: Status = Field(
        ...,
        description='Target status. `running` and `waiting` are system-only and cannot be set by clients.',
    )


class PatchRunBody(BaseModel):
    questions: list[RunQuestion] | None = Field(
        None, description='Questions with updated `answer` values.'
    )
    suggestions: RunSuggestions | None = None


class PatchJobBody(BaseModel):
    options: JobOptions | None = None


class ContextEntry(BaseModel):
    id: UUID = Field(..., description='Immutable identifier assigned at creation.')
    name: str = Field(..., description='Human-readable name for this context entry.')
    text: str = Field(..., description='The context text injected into LLM prompts.')


class PaginatedContexts(BaseModel):
    data: list[ContextEntry]
    next_page_token: str | None = Field(
        None,
        description='Opaque cursor; pass as `page_token` on next request. Null when no more pages.',
    )


class CreateContextBody(BaseModel):
    name: str = Field(..., description='Human-readable name for this context entry.')
    text: str = Field(..., description='The context text injected into LLM prompts.')


class UpdateContextBody(BaseModel):
    name: str | None = Field(None, description='Updated name. Null leaves unchanged.')
    text: str | None = Field(
        None, description='Updated context text. Null leaves unchanged.'
    )


class RagRetrieval(BaseModel):
    enabled: bool | None = Field(
        True, description='Whether RAG retrieval is enabled for this chat.'
    )
    max_sources: conint(ge=1, le=20) | None = Field(
        5, description='Maximum number of source documents to retrieve per query.'
    )
    minimum_score: float | None = Field(
        0.0, description='Minimum similarity score for retrieved sources.'
    )


class SourceDoc(BaseModel):
    document_id: UUID = Field(..., description='UUID of the source document.')
    title: str = Field(..., description='Document title.')
    summary: str | None = Field(
        '', description="Brief summary of the document's content."
    )
    date_month: str | None = Field(
        '', description='YYYY-MM month label for the document.'
    )
    score: float = Field(..., description='Vector similarity score.')


class Role(Enum):
    user = 'user'
    assistant = 'assistant'


class ChatMessage(BaseModel):
    id: UUID = Field(..., description='Unique message identifier.')
    external_id: str | None = Field(
        None,
        description='External identifier assigned by the LLM provider (e.g. Ollama message ID).',
    )
    role: Role = Field(..., description='Message author.')
    content: str = Field(..., description='Message text.')
    sources: list[SourceDoc] | None = Field(
        None, description='Retrieved source documents (only set on assistant messages).'
    )
    created_at: datetime = Field(..., description='ISO 8601 creation timestamp.')


class ChatSummary(BaseModel):
    id: str = Field(..., description='Chat UUID.')
    title: str | None = Field(
        None,
        description='Auto-derived from the first user message (first 60 chars). Null until the first message is sent.',
    )
    system_prompt: str | None = Field(
        None, description='Optional freeform context injected into every system prompt.'
    )
    rag_retrieval: RagRetrieval
    created_at: datetime = Field(..., description='ISO 8601 creation timestamp.')
    updated_at: datetime = Field(..., description='ISO 8601 last-updated timestamp.')


class ChatDetail(ChatSummary):
    messages: list[ChatMessage] | None = Field(
        None, description='All messages in the chat in chronological order.'
    )


class PaginatedChats(BaseModel):
    data: list[ChatSummary]
    next_page_token: str | None = Field(
        None,
        description='Opaque cursor; pass as `page_token` on next request. Null when no more pages.',
    )


class CreateChatBody(BaseModel):
    system_prompt: str | None = Field(
        '', description='Optional freeform context injected into every system prompt.'
    )
    rag_retrieval: RagRetrieval | None = None


class PatchChatBody(BaseModel):
    title: str | None = Field(None, description='Override the auto-derived title.')
    system_prompt: str | None = Field(
        None, description='Updated system prompt. Null clears it.'
    )
    rag_retrieval: RagRetrieval | None = None


class SendMessageBody(BaseModel):
    content: str = Field(..., description="The user's message text.")


import base64
import json as _json


def encode_page_token(sort_key: str, row_id: str) -> str:
    payload = _json.dumps({"k": sort_key, "id": row_id})
    return base64.urlsafe_b64encode(payload.encode()).decode()


def decode_page_token(token: str) -> tuple[str, str]:
    payload = _json.loads(base64.urlsafe_b64decode(token.encode()).decode())
    return payload["k"], payload["id"]
