# generated by datamodel-codegen:
#   filename:  openapi.yaml
#
# NOTE: The pagination helpers below (encode_page_token / decode_page_token)
# are hand-written and must be re-added after each `make generate-server` run.

from __future__ import annotations

import base64
import json
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field, RootModel, conint


# ── Pagination helpers ─────────────────────────────────────────────────────────

def encode_page_token(sort_key: Any, row_id: str) -> str:
    data = json.dumps({"k": sort_key, "id": row_id}, separators=(",", ":"))
    return base64.urlsafe_b64encode(data.encode()).decode().rstrip("=")


def decode_page_token(token: str) -> Optional[dict]:
    try:
        padding = 4 - len(token) % 4
        if padding != 4:
            token += "=" * padding
        return json.loads(base64.urlsafe_b64decode(token))
    except Exception:
        return None


class StageState(Enum):
    pending = 'pending'
    running = 'running'
    waiting = 'waiting'
    error = 'error'
    done = 'done'


class ErrorResponse(BaseModel):
    error: str = Field(..., description='Human-readable error message.')


class OkResponse(BaseModel):
    ok: bool


class PipelineStageConfig(BaseModel):
    name: str = Field(..., description='Stage identifier (e.g. `ocr`, `clarify`).')
    type: str = Field(..., description='Stage handler type (e.g. `llm_text`, `embed`).')
    model: str | None = Field(None, description='Model override for LLM stages.')


class PipelineSummary(BaseModel):
    id: str = Field(..., description='Pipeline identifier (filename stem).')
    name: str = Field(..., description='Human-readable pipeline name.')
    stage_count: int = Field(..., description='Number of stages in the pipeline.')


class PipelineDetail(BaseModel):
    id: str
    name: str
    stages: list[PipelineStageConfig]


class PaginatedPipelines(BaseModel):
    data: list[PipelineSummary]
    next_page_token: str | None = Field(None, alias='nextPageToken')


class DocumentSummary(BaseModel):
    id: UUID = Field(..., description='Unique document identifier.')
    title: str | None = Field(None, description='Human-readable title.')
    needs_context: bool = Field(
        ...,
        description="True if the document's current stage is blocked waiting for context.",
    )
    created_at: datetime
    updated_at: datetime


class PaginatedDocuments(BaseModel):
    data: list[DocumentSummary]
    next_page_token: str | None = Field(None, alias='nextPageToken')


class StageDisplay(BaseModel):
    name: str = Field(..., description='Pipeline stage name (e.g. `ocr`, `clarify`).')
    fields: dict[str, str] = Field(
        ...,
        description='Map of field name to text value for each output produced by the stage.',
    )


class JobSummary(BaseModel):
    doc_id: UUID
    title: str | None = Field(None, description='Denormalized document title.')
    current_stage: str
    stage_state: StageState
    needs_context: bool
    created_at: datetime
    updated_at: datetime


class PaginatedJobs(BaseModel):
    data: list[JobSummary]
    next_page_token: str | None = Field(None, alias='nextPageToken')


class JobEventRecord(BaseModel):
    id: int = Field(
        ..., description='Monotonically increasing internal event ID (used as cursor).'
    )
    timestamp: datetime
    stage: str
    event_type: str
    data: dict[str, Any] | None = None


class PaginatedJobEvents(BaseModel):
    data: list[JobEventRecord]
    next_page_token: str | None = Field(
        None,
        alias='nextPageToken',
        description='Pass as `afterId` on the next request to fetch subsequent events.',
    )


class ReplayStage(BaseModel):
    name: str


class ClarificationRequest(BaseModel):
    segment: str
    question: str


class Type(Enum):
    approve = 'approve'


class ApproveEvent(BaseModel):
    type: Literal['approve']
    edited_text: str | None = ''


class Type1(Enum):
    reject = 'reject'


class RejectEvent(BaseModel):
    type: Literal['reject']


class Type2(Enum):
    clarify = 'clarify'


class ClarifyEvent(BaseModel):
    type: Literal['clarify']
    answers: dict[str, str] | None = {}
    free_prompt: str | None = ''
    edited_text: str | None = ''


class Type3(Enum):
    retry = 'retry'


class RetryEvent(BaseModel):
    type: Literal['retry']


class Type4(Enum):
    stop = 'stop'


class StopEvent(BaseModel):
    type: Literal['stop']


class Type5(Enum):
    replay = 'replay'


class ReplayEvent(BaseModel):
    type: Literal['replay']
    stage: str = Field(..., description='Name of the pipeline stage to rewind to.')


class Type6(Enum):
    provide_context = 'provide_context'


class ProvideContextEvent(BaseModel):
    type: Literal['provide_context']
    document_context: str | None = ''
    context_ref: str | None = None


class Type7(Enum):
    clear_errors = 'clear_errors'


class ClearErrorsEvent(BaseModel):
    type: Literal['clear_errors']


# NOTE: codegen emits a RootModel here; replaced with Annotated union so that
# FastAPI resolves the discriminator and api.py can access body.type directly.
JobEventBody = Annotated[
    ApproveEvent
    | RejectEvent
    | ClarifyEvent
    | RetryEvent
    | StopEvent
    | ReplayEvent
    | ProvideContextEvent
    | ClearErrorsEvent,
    Field(discriminator='type'),
]


class ContextEntry(BaseModel):
    id: UUID = Field(..., description='Immutable identifier assigned at creation.')
    name: str = Field(..., description='Human-readable name for this context entry.')
    text: str = Field(..., description='The context text injected into LLM prompts.')


class PaginatedContexts(BaseModel):
    data: list[ContextEntry]
    next_page_token: str | None = Field(None, alias='nextPageToken')


class CreateContextBody(BaseModel):
    name: str
    text: str


class UpdateContextBody(BaseModel):
    name: str | None = None
    text: str | None = None


class PatchDocumentBody(BaseModel):
    title: str | None = None
    document_context: str | None = None
    context_ref: str | None = Field(
        None, description='UUID of a context entry to link, or null to unlink.'
    )


class Role(Enum):
    user = 'user'
    assistant = 'assistant'


class ChatMessage(BaseModel):
    role: Role
    content: str


class ChatRequest(BaseModel):
    messages: list[ChatMessage]
    context: str | None = Field(
        '', description='Optional free-text context injected into the system prompt.'
    )
    top_k: conint(ge=1, le=20) | None = Field(
        5, description='Number of vector search results to retrieve per turn.'
    )


class SourceDoc(BaseModel):
    doc_id: UUID
    title: str
    summary: str | None = ''
    date_month: str | None = Field(
        '', description='YYYY-MM month label for the document.'
    )
    score: float


class DocumentDetail(BaseModel):
    id: UUID
    title: str | None = None
    document_context: str = Field(
        ..., description='Free-text context attached by the user to guide LLM stages.'
    )
    context_ref: str | None = Field(
        None, description='UUID of a saved context entry linked to this document.'
    )
    has_image: bool = Field(..., description='True if a source PNG image is available.')
    stage_displays: list[StageDisplay] = Field(
        ..., description='Completed stage outputs available for display.'
    )
    created_at: datetime
    updated_at: datetime


class ReviewDetail(BaseModel):
    stage_name: str
    input_field: str | None = None
    output_field: str | None = None
    input_text: str
    output_text: str
    is_single_output: bool
    confidence: str
    qa_rounds: int
    clarification_requests: list[ClarificationRequest]
    context_updates: str


class JobDetail(BaseModel):
    doc_id: UUID
    current_stage: str
    stage_state: StageState
    needs_context: bool = Field(
        ...,
        description='True if the current stage is blocked waiting for context input.',
    )
    context_required: bool = Field(
        ...,
        description='True when the current stage requires context before it can run at all.',
    )
    review: ReviewDetail | None = Field(
        None, description='Present when the document is waiting for human review.'
    )
    replay_stages: list[ReplayStage] = Field(
        ..., description='Completed stages the job can be rewound to.'
    )
