# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-03-29T13:46:28+00:00
#
# NOTE: The pagination helpers below (encode_page_token / decode_page_token)
# and JobEventBody are hand-written and must be re-added after each `make generate` run.

from __future__ import annotations

import base64
import json
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field, RootModel, conint


# ── Pagination helpers ─────────────────────────────────────────────────────────

def encode_page_token(sort_key: Any, row_id: str) -> str:
    data = json.dumps({"k": sort_key, "id": row_id}, separators=(",", ":"))
    return base64.urlsafe_b64encode(data.encode()).decode().rstrip("=")


def decode_page_token(token: str) -> Optional[dict]:
    try:
        padding = 4 - len(token) % 4
        if padding != 4:
            token += "=" * padding
        return json.loads(base64.urlsafe_b64decode(token))
    except Exception:
        return None


class StageState(Enum):
    pending = 'pending'
    running = 'running'
    waiting = 'waiting'
    error = 'error'
    done = 'done'


class ErrorResponse(BaseModel):
    error: str = Field(..., description='Human-readable error message.')


class OkResponse(BaseModel):
    ok: bool = Field(..., description='Always true on success.')


class PipelineStageConfig(BaseModel):
    name: str = Field(..., description='Stage identifier (e.g. `ocr`, `clarify`).')
    type: str = Field(..., description='Stage handler type (e.g. `llm_text`, `embed`).')
    model: str | None = Field(None, description='Model override for LLM stages.')


class PipelineSummary(BaseModel):
    id: str = Field(..., description='Pipeline identifier (filename stem).')
    name: str = Field(..., description='Human-readable pipeline name.')
    stage_count: int = Field(..., description='Number of stages in the pipeline.')


class PipelineDetail(BaseModel):
    id: str = Field(..., description='Pipeline identifier (filename stem).')
    name: str = Field(..., description='Human-readable pipeline name.')
    stages: list[PipelineStageConfig] = Field(
        ..., description='Ordered list of stage configurations.'
    )


class PaginatedPipelines(BaseModel):
    data: list[PipelineSummary]
    next_page_token: str | None = Field(
        None,
        alias='nextPageToken',
        description='Opaque cursor; pass as `pageToken` on next request. Null when no more pages.',
    )


class DocumentSummary(BaseModel):
    id: UUID = Field(..., description='Unique document identifier.')
    title: str | None = Field(None, description='Human-readable title.')
    needs_context: bool = Field(
        ...,
        description="True if the document's current stage is blocked waiting for context.",
    )
    created_at: datetime = Field(..., description='ISO 8601 creation timestamp.')
    updated_at: datetime = Field(..., description='ISO 8601 last-updated timestamp.')


class PaginatedDocuments(BaseModel):
    data: list[DocumentSummary]
    next_page_token: str | None = Field(
        None,
        alias='nextPageToken',
        description='Opaque cursor; pass as `pageToken` on next request. Null when no more pages.',
    )


class StageDisplay(BaseModel):
    name: str = Field(..., description='Pipeline stage name (e.g. `ocr`, `clarify`).')
    fields: dict[str, str] = Field(
        ...,
        description='Map of field name to text value for each output produced by the stage.',
    )


class JobSummary(BaseModel):
    doc_id: UUID = Field(..., description='UUID of the document this job belongs to.')
    title: str | None = Field(None, description='Denormalized document title.')
    current_stage: str = Field(
        ..., description='Name of the stage the document is currently in.'
    )
    stage_state: StageState
    needs_context: bool = Field(
        ...,
        description='True if the current stage is blocked waiting for context input.',
    )
    created_at: datetime = Field(..., description='ISO 8601 creation timestamp.')
    updated_at: datetime = Field(..., description='ISO 8601 last-updated timestamp.')


class PaginatedJobs(BaseModel):
    data: list[JobSummary]
    next_page_token: str | None = Field(
        None,
        alias='nextPageToken',
        description='Opaque cursor; pass as `pageToken` on next request. Null when no more pages.',
    )


class JobEventRecord(BaseModel):
    id: int = Field(
        ..., description='Monotonically increasing internal event ID (used as cursor).'
    )
    timestamp: datetime = Field(
        ..., description='ISO 8601 timestamp of when the event was recorded.'
    )
    stage: str = Field(..., description='Pipeline stage name at time of event.')
    event_type: str = Field(
        ..., description='Type of event (e.g. `approved`, `completed`, `error`).'
    )
    data: dict[str, Any] | None = Field(None, description='Optional event payload.')


class PaginatedJobEvents(BaseModel):
    data: list[JobEventRecord]
    next_page_token: str | None = Field(
        None,
        alias='nextPageToken',
        description='Opaque cursor; pass as `pageToken` on next request. Null when no more pages.',
    )


class PatchJobBody(BaseModel):
    embed_image: bool | None = Field(
        None,
        description='Set to true/false to control image embedding for the embed stage.',
    )


class ReplayStage(BaseModel):
    name: str = Field(..., description='Pipeline stage name.')


class ClarificationRequest(BaseModel):
    segment: str = Field(
        ..., description='The text segment that prompted the question.'
    )
    question: str = Field(
        ..., description='The clarification question to present to the user.'
    )


class Type(Enum):
    approve = 'approve'


class ApproveEvent(BaseModel):
    type: Literal['approve'] = Field(..., description='Event discriminator.')
    edited_text: str | None = Field(
        '',
        description='Replacement text for the LLM output. Empty string keeps the original.',
    )


class Type1(Enum):
    reject = 'reject'


class RejectEvent(BaseModel):
    type: Literal['reject'] = Field(..., description='Event discriminator.')


class Type2(Enum):
    clarify = 'clarify'


class ClarifyEvent(BaseModel):
    type: Literal['clarify'] = Field(..., description='Event discriminator.')
    answers: dict[str, str] | None = Field(
        {},
        description='Map of question text to answer text for each clarification request.',
    )
    free_prompt: str | None = Field(
        '', description='Additional instruction appended to the retry prompt.'
    )
    edited_text: str | None = Field(
        '', description='Optionally replace the existing output before retrying.'
    )


class Type3(Enum):
    retry = 'retry'


class RetryEvent(BaseModel):
    type: Literal['retry'] = Field(..., description='Event discriminator.')


class Type4(Enum):
    stop = 'stop'


class StopEvent(BaseModel):
    type: Literal['stop'] = Field(..., description='Event discriminator.')


class Type5(Enum):
    replay = 'replay'


class ReplayEvent(BaseModel):
    type: Literal['replay'] = Field(..., description='Event discriminator.')
    stage: str = Field(..., description='Name of the pipeline stage to rewind to.')


class Type6(Enum):
    provide_context = 'provide_context'


class ProvideContextEvent(BaseModel):
    type: Literal['provide_context'] = Field(..., description='Event discriminator.')
    document_context: str | None = Field(
        '', description='Free-text context to attach to the document.'
    )
    context_ref: str | None = Field(
        None, description='UUID of a saved context entry to link.'
    )


class Type7(Enum):
    clear_errors = 'clear_errors'


class ClearErrorsEvent(BaseModel):
    type: Literal['clear_errors'] = Field(..., description='Event discriminator.')


# NOTE: codegen emits a RootModel here; replaced with Annotated union so that
# FastAPI can parse the discriminated union directly from the request body.
JobEventBody = Annotated[
    ApproveEvent
    | RejectEvent
    | ClarifyEvent
    | RetryEvent
    | StopEvent
    | ReplayEvent
    | ProvideContextEvent
    | ClearErrorsEvent,
    Field(discriminator='type'),
]


class ContextEntry(BaseModel):
    id: UUID = Field(..., description='Immutable identifier assigned at creation.')
    name: str = Field(..., description='Human-readable name for this context entry.')
    text: str = Field(..., description='The context text injected into LLM prompts.')


class PaginatedContexts(BaseModel):
    data: list[ContextEntry]
    next_page_token: str | None = Field(
        None,
        alias='nextPageToken',
        description='Opaque cursor; pass as `pageToken` on next request. Null when no more pages.',
    )


class CreateContextBody(BaseModel):
    name: str = Field(..., description='Human-readable name for this context entry.')
    text: str = Field(..., description='The context text injected into LLM prompts.')


class UpdateContextBody(BaseModel):
    name: str | None = Field(None, description='Updated name. Null leaves unchanged.')
    text: str | None = Field(
        None, description='Updated context text. Null leaves unchanged.'
    )


class PatchDocumentBody(BaseModel):
    title: str | None = Field(
        None, description='Updated document title. Null clears the title.'
    )
    document_context: str | None = Field(
        None, description='Free-text context to attach to the document. Null clears it.'
    )
    context_ref: str | None = Field(
        None, description='UUID of a context entry to link, or null to unlink.'
    )


class SourceDoc(BaseModel):
    doc_id: UUID = Field(..., description='UUID of the source document.')
    title: str = Field(..., description='Document title.')
    summary: str | None = Field(
        '', description="Brief summary of the document's content."
    )
    date_month: str | None = Field(
        '', description='YYYY-MM month label for the document.'
    )
    score: float = Field(..., description='Vector similarity score.')


class ChatSessionSummary(BaseModel):
    id: str = Field(..., description='Session UUID.')
    title: str = Field(
        ..., description='Auto-derived from the first user message (first 60 chars).'
    )
    context: str = Field(
        ..., description='Optional freeform context injected into every system prompt.'
    )
    top_k: int = Field(
        ..., description='Number of Qdrant results to retrieve per query.'
    )
    created_at: str = Field(..., description='ISO 8601 creation timestamp.')
    updated_at: str = Field(..., description='ISO 8601 last-updated timestamp.')
    message_count: int = Field(
        ..., description='Total number of messages in the session.'
    )


class Role(Enum):
    user = 'user'
    assistant = 'assistant'


class ChatMessageRecord(BaseModel):
    id: int = Field(..., description='Auto-increment row ID; defines message ordering.')
    role: Role = Field(..., description='Message author.')
    content: str = Field(..., description='Message text.')
    sources: list[SourceDoc] | None = Field(
        None, description='Retrieved source documents (only set on assistant messages).'
    )
    created_at: str = Field(..., description='ISO 8601 creation timestamp.')


class CreateChatSessionBody(BaseModel):
    context: str | None = Field(
        '', description='Optional freeform context injected into every system prompt.'
    )
    top_k: conint(ge=1, le=20) | None = Field(
        5, description='Number of Qdrant results to retrieve per query.'
    )


class PatchChatSessionBody(BaseModel):
    title: str | None = Field(None, description='Override the auto-derived title.')
    context: str | None = Field(
        None, description='Optional freeform context injected into every system prompt.'
    )
    top_k: conint(ge=1, le=20) | None = Field(
        None, description='Number of Qdrant results to retrieve per query.'
    )


class SendMessageBody(BaseModel):
    content: str = Field(..., description="The user's message text.")


class PaginatedChatSessions(BaseModel):
    data: list[ChatSessionSummary]
    next_before_id: str | None = Field(
        None,
        description='Pass as `before_id` to fetch the next page. Null when no more pages.',
    )


class DocumentDetail(BaseModel):
    id: UUID = Field(..., description='Unique document identifier.')
    title: str | None = Field(None, description='Human-readable document title.')
    document_context: str = Field(
        ..., description='Free-text context attached by the user to guide LLM stages.'
    )
    context_ref: str | None = Field(
        None, description='UUID of a saved context entry linked to this document.'
    )
    current_job_id: str | None = Field(
        None, description='UUID of the active job row for the current pipeline stage.'
    )
    has_image: bool = Field(..., description='True if a source PNG image is available.')
    stage_displays: list[StageDisplay] = Field(
        ..., description='Completed stage outputs available for display.'
    )
    created_at: datetime = Field(..., description='ISO 8601 creation timestamp.')
    updated_at: datetime = Field(..., description='ISO 8601 last-updated timestamp.')


class ReviewDetail(BaseModel):
    stage_name: str = Field(..., description='Name of the stage awaiting review.')
    input_field: str | None = Field(
        None, description='Source field name fed into the LLM prompt.'
    )
    output_field: str | None = Field(
        None, description='Field name where the LLM output is stored.'
    )
    input_text: str = Field(..., description='The text sent to the LLM.')
    output_text: str = Field(..., description="The LLM's output awaiting approval.")
    is_single_output: bool = Field(
        ..., description='True when the stage writes a single output field.'
    )
    confidence: str = Field(..., description='LLM-reported confidence in the output.')
    qa_rounds: int = Field(
        ..., description='Number of clarification rounds completed so far.'
    )
    clarification_requests: list[ClarificationRequest] = Field(
        ...,
        description='Questions the LLM raised that need answers before it can proceed.',
    )
    document_context_update: str = Field(
        ...,
        description="Suggested update to the document's context field, proposed by the LLM.",
    )
    linked_context_update: str = Field(
        ...,
        description='Suggested update to the linked context entry, proposed by the LLM.',
    )
    context_ref: str | None = Field(
        None, description='UUID of the linked context entry, if any.'
    )


class ChatSessionDetail(BaseModel):
    id: str = Field(..., description='Session UUID.')
    title: str = Field(
        ..., description='Auto-derived from the first user message (first 60 chars).'
    )
    context: str = Field(
        ..., description='Optional freeform context injected into every system prompt.'
    )
    top_k: int = Field(
        ..., description='Number of Qdrant results to retrieve per query.'
    )
    created_at: str = Field(..., description='ISO 8601 creation timestamp.')
    updated_at: str = Field(..., description='ISO 8601 last-updated timestamp.')
    messages: list[ChatMessageRecord] = Field(
        ..., description='All messages in the session in chronological order.'
    )


class JobDetail(BaseModel):
    id: str = Field(
        ..., description='UUID of the active job row for the current stage.'
    )
    doc_id: UUID = Field(..., description='UUID of the document this job belongs to.')
    current_stage: str = Field(
        ..., description='Name of the stage the document is currently in.'
    )
    stage_state: StageState
    needs_context: bool = Field(
        ...,
        description='True if the current stage is blocked waiting for context input.',
    )
    context_required: bool = Field(
        ...,
        description='True when the current stage requires context before it can run at all.',
    )
    embed_image: bool = Field(
        ..., description='Whether the embed stage should include a visual image vector.'
    )
    review: ReviewDetail | None = Field(
        None, description='Present when the document is waiting for human review.'
    )
    replay_stages: list[ReplayStage] = Field(
        ..., description='Completed stages the job can be rewound to.'
    )
