// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package schema

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AuthentikScopes = "authentik.Scopes"
)

// Defines values for ChatMessageRole.
const (
	Assistant ChatMessageRole = "assistant"
	User      ChatMessageRole = "user"
)

// Valid indicates whether the value is a known member of the ChatMessageRole enum.
func (e ChatMessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusDone    JobStatus = "done"
	JobStatusError   JobStatus = "error"
	JobStatusPending JobStatus = "pending"
	JobStatusRunning JobStatus = "running"
	JobStatusWaiting JobStatus = "waiting"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusDone:
		return true
	case JobStatusError:
		return true
	case JobStatusPending:
		return true
	case JobStatusRunning:
		return true
	case JobStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for PutJobStatusBodyStatus.
const (
	PutJobStatusBodyStatusDone    PutJobStatusBodyStatus = "done"
	PutJobStatusBodyStatusError   PutJobStatusBodyStatus = "error"
	PutJobStatusBodyStatusPending PutJobStatusBodyStatus = "pending"
)

// Valid indicates whether the value is a known member of the PutJobStatusBodyStatus enum.
func (e PutJobStatusBodyStatus) Valid() bool {
	switch e {
	case PutJobStatusBodyStatusDone:
		return true
	case PutJobStatusBodyStatusError:
		return true
	case PutJobStatusBodyStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for RunConfidence.
const (
	High   RunConfidence = "high"
	Low    RunConfidence = "low"
	Medium RunConfidence = "medium"
)

// Valid indicates whether the value is a known member of the RunConfidence enum.
func (e RunConfidence) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for SortOrder.
const (
	SortOrderCreatedAsc  SortOrder = "created_asc"
	SortOrderCreatedDesc SortOrder = "created_desc"
	SortOrderPipeline    SortOrder = "pipeline"
	SortOrderTitleAsc    SortOrder = "title_asc"
	SortOrderTitleDesc   SortOrder = "title_desc"
)

// Valid indicates whether the value is a known member of the SortOrder enum.
func (e SortOrder) Valid() bool {
	switch e {
	case SortOrderCreatedAsc:
		return true
	case SortOrderCreatedDesc:
		return true
	case SortOrderPipeline:
		return true
	case SortOrderTitleAsc:
		return true
	case SortOrderTitleDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListDocumentsParamsSort.
const (
	ListDocumentsParamsSortCreatedAsc  ListDocumentsParamsSort = "created_asc"
	ListDocumentsParamsSortCreatedDesc ListDocumentsParamsSort = "created_desc"
	ListDocumentsParamsSortPipeline    ListDocumentsParamsSort = "pipeline"
	ListDocumentsParamsSortTitleAsc    ListDocumentsParamsSort = "title_asc"
	ListDocumentsParamsSortTitleDesc   ListDocumentsParamsSort = "title_desc"
)

// Valid indicates whether the value is a known member of the ListDocumentsParamsSort enum.
func (e ListDocumentsParamsSort) Valid() bool {
	switch e {
	case ListDocumentsParamsSortCreatedAsc:
		return true
	case ListDocumentsParamsSortCreatedDesc:
		return true
	case ListDocumentsParamsSortPipeline:
		return true
	case ListDocumentsParamsSortTitleAsc:
		return true
	case ListDocumentsParamsSortTitleDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListJobsParamsSort.
const (
	ListJobsParamsSortCreatedAsc  ListJobsParamsSort = "created_asc"
	ListJobsParamsSortCreatedDesc ListJobsParamsSort = "created_desc"
	ListJobsParamsSortPipeline    ListJobsParamsSort = "pipeline"
	ListJobsParamsSortTitleAsc    ListJobsParamsSort = "title_asc"
	ListJobsParamsSortTitleDesc   ListJobsParamsSort = "title_desc"
)

// Valid indicates whether the value is a known member of the ListJobsParamsSort enum.
func (e ListJobsParamsSort) Valid() bool {
	switch e {
	case ListJobsParamsSortCreatedAsc:
		return true
	case ListJobsParamsSortCreatedDesc:
		return true
	case ListJobsParamsSortPipeline:
		return true
	case ListJobsParamsSortTitleAsc:
		return true
	case ListJobsParamsSortTitleDesc:
		return true
	default:
		return false
	}
}

// Artifact A file artifact associated with a document. Source images uploaded by the user
// are stored as artifacts with `created_job_id: null`. Pipeline stages (e.g. OCR)
// may produce additional artifacts such as extracted text files.
type Artifact struct {
	// ContentType MIME type (e.g. `image/png`, `text/plain`).
	ContentType string `json:"content_type"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// CreatedJobId UUID of the job that created this artifact. Null for source artifacts created during ingest.
	CreatedJobId *openapi_types.UUID `json:"created_job_id,omitempty"`

	// Filename Original filename of the artifact.
	Filename string `json:"filename"`

	// Id Unique artifact identifier.
	Id openapi_types.UUID `json:"id"`

	// UpdatedAt ISO 8601 last-updated timestamp.
	UpdatedAt time.Time `json:"updated_at"`
}

// ChatDetail defines model for ChatDetail.
type ChatDetail struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// Id Chat UUID.
	Id string `json:"id"`

	// Messages All messages in the chat in chronological order.
	Messages *[]ChatMessage `json:"messages,omitempty"`

	// RagRetrieval RAG retrieval configuration for a chat.
	RagRetrieval RagRetrieval `json:"rag_retrieval"`

	// SystemPrompt Optional freeform context injected into every system prompt.
	SystemPrompt *string `json:"system_prompt,omitempty"`

	// Title Auto-derived from the first user message (first 60 chars). Null until the first message is sent.
	Title *string `json:"title,omitempty"`

	// UpdatedAt ISO 8601 last-updated timestamp.
	UpdatedAt time.Time `json:"updated_at"`
}

// ChatMessage A single message turn in a chat.
type ChatMessage struct {
	// Content Message text.
	Content string `json:"content"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// ExternalId External identifier assigned by the LLM provider (e.g. Ollama message ID).
	ExternalId *string `json:"external_id,omitempty"`

	// Id Unique message identifier.
	Id openapi_types.UUID `json:"id"`

	// Role Message author.
	Role ChatMessageRole `json:"role"`

	// Sources Retrieved source documents (only set on assistant messages).
	Sources *[]SourceDoc `json:"sources,omitempty"`
}

// ChatMessageRole Message author.
type ChatMessageRole string

// ChatSummary Lightweight chat representation used in list views.
type ChatSummary struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// Id Chat UUID.
	Id string `json:"id"`

	// RagRetrieval RAG retrieval configuration for a chat.
	RagRetrieval RagRetrieval `json:"rag_retrieval"`

	// SystemPrompt Optional freeform context injected into every system prompt.
	SystemPrompt *string `json:"system_prompt,omitempty"`

	// Title Auto-derived from the first user message (first 60 chars). Null until the first message is sent.
	Title *string `json:"title,omitempty"`

	// UpdatedAt ISO 8601 last-updated timestamp.
	UpdatedAt time.Time `json:"updated_at"`
}

// ContextEntry A named reusable context snippet with an immutable UUID.
type ContextEntry struct {
	// Id Immutable identifier assigned at creation.
	Id openapi_types.UUID `json:"id"`

	// Name Human-readable name for this context entry.
	Name string `json:"name"`

	// Text The context text injected into LLM prompts.
	Text string `json:"text"`
}

// CreateChatBody Options for creating a new chat.
type CreateChatBody struct {
	// RagRetrieval RAG retrieval configuration for a chat.
	RagRetrieval *RagRetrieval `json:"rag_retrieval,omitempty"`

	// SystemPrompt Optional freeform context injected into every system prompt.
	SystemPrompt *string `json:"system_prompt,omitempty"`
}

// CreateContextBody Payload for creating a new context entry.
type CreateContextBody struct {
	// Name Human-readable name for this context entry.
	Name string `json:"name"`

	// Text The context text injected into LLM prompts.
	Text string `json:"text"`
}

// DocumentDetail defines model for DocumentDetail.
type DocumentDetail struct {
	// AdditionalContext Free-text context attached by the user to guide LLM stages.
	AdditionalContext *string `json:"additional_context,omitempty"`

	// Artifacts Files associated with this document (e.g. source image).
	Artifacts *[]Artifact `json:"artifacts,omitempty"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// CurrentJobId UUID of the most recently active job for this document.
	CurrentJobId *openapi_types.UUID `json:"current_job_id,omitempty"`

	// Id Unique document identifier.
	Id openapi_types.UUID `json:"id"`

	// LinkedContexts UUIDs of saved context entries linked to this document.
	LinkedContexts *[]openapi_types.UUID `json:"linked_contexts,omitempty"`

	// Series Series name grouping this document with related documents for corpus embedding.
	Series *string `json:"series,omitempty"`

	// Title Human-readable title.
	Title *string `json:"title,omitempty"`

	// UpdatedAt ISO 8601 last-updated timestamp.
	UpdatedAt time.Time `json:"updated_at"`
}

// DocumentSummary Lightweight document representation used in list views.
type DocumentSummary struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// CurrentJobId UUID of the most recently active job for this document.
	CurrentJobId *openapi_types.UUID `json:"current_job_id,omitempty"`

	// Id Unique document identifier.
	Id openapi_types.UUID `json:"id"`

	// Series Series name grouping this document with related documents for corpus embedding.
	Series *string `json:"series,omitempty"`

	// Title Human-readable title.
	Title *string `json:"title,omitempty"`

	// UpdatedAt ISO 8601 last-updated timestamp.
	UpdatedAt time.Time `json:"updated_at"`
}

// EmbedOptions Options specific to the embed stage.
type EmbedOptions struct {
	// EmbedImage Whether to include a visual image vector in addition to the text vector.
	EmbedImage *bool `json:"embed_image,omitempty"`
}

// ErrorResponse Generic error body.
type ErrorResponse struct {
	// Error Human-readable error message.
	Error string `json:"error"`
}

// JobDetail defines model for JobDetail.
type JobDetail struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// DocumentId UUID of the document this job belongs to.
	DocumentId openapi_types.UUID `json:"document_id"`

	// Id Unique job identifier.
	Id openapi_types.UUID `json:"id"`

	// Options Per-job configuration options.
	Options *JobOptions `json:"options,omitempty"`

	// Runs Ordered list of LLM round trips for this job. Appended on each execution.
	Runs *[]Run `json:"runs,omitempty"`

	// Stage Pipeline stage this job executes (e.g. `ocr`, `clarify`).
	Stage string `json:"stage"`

	// Status Execution status of a job.
	Status JobStatus `json:"status"`

	// Title Denormalized document title.
	Title *string `json:"title,omitempty"`

	// UpdatedAt ISO 8601 last-updated timestamp.
	UpdatedAt time.Time `json:"updated_at"`
}

// JobOptions Per-job configuration options.
type JobOptions struct {
	// Embed Options specific to the embed stage.
	Embed *EmbedOptions `json:"embed,omitempty"`

	// RequireContext Whether this stage requires context before it can run.
	RequireContext *bool `json:"require_context,omitempty"`
}

// JobStatus Execution status of a job.
type JobStatus string

// JobSummary Lightweight job representation used in list views.
type JobSummary struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// DocumentId UUID of the document this job belongs to.
	DocumentId openapi_types.UUID `json:"document_id"`

	// Id Unique job identifier.
	Id openapi_types.UUID `json:"id"`

	// Stage Pipeline stage this job executes (e.g. `ocr`, `clarify`).
	Stage string `json:"stage"`

	// Status Execution status of a job.
	Status JobStatus `json:"status"`

	// Title Denormalized document title.
	Title *string `json:"title,omitempty"`

	// UpdatedAt ISO 8601 last-updated timestamp.
	UpdatedAt time.Time `json:"updated_at"`
}

// OkResponse Simple success acknowledgement.
type OkResponse struct {
	// Ok Always true on success.
	Ok bool `json:"ok"`
}

// PaginatedChats Paginated list of chats ordered by most recently updated.
type PaginatedChats struct {
	Data []ChatSummary `json:"data"`

	// NextPageToken Opaque cursor; pass as `page_token` on next request. Null when no more pages.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// PaginatedContexts Paginated list of context entries.
type PaginatedContexts struct {
	Data []ContextEntry `json:"data"`

	// NextPageToken Opaque cursor; pass as `page_token` on next request. Null when no more pages.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// PaginatedDocuments Paginated list of document summaries.
type PaginatedDocuments struct {
	Data []DocumentSummary `json:"data"`

	// NextPageToken Opaque cursor; pass as `page_token` on next request. Null when no more pages.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// PaginatedJobs Paginated list of job summaries.
type PaginatedJobs struct {
	Data []JobSummary `json:"data"`

	// NextPageToken Opaque cursor; pass as `page_token` on next request. Null when no more pages.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// PaginatedPipelines Paginated list of pipelines.
type PaginatedPipelines struct {
	Data []Pipeline `json:"data"`

	// NextPageToken Opaque cursor; pass as `page_token` on next request. Null when no more pages.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// PatchChatBody Fields to update on an existing chat. Omitted fields are unchanged.
type PatchChatBody struct {
	// RagRetrieval RAG retrieval configuration for a chat.
	RagRetrieval *RagRetrieval `json:"rag_retrieval,omitempty"`

	// SystemPrompt Updated system prompt. Null clears it.
	SystemPrompt *string `json:"system_prompt,omitempty"`

	// Title Override the auto-derived title.
	Title *string `json:"title,omitempty"`
}

// PatchDocumentBody Fields to update on a document. Only present fields are applied.
type PatchDocumentBody struct {
	// AdditionalContext Free-text context to attach to the document. Null clears it.
	AdditionalContext *string `json:"additional_context,omitempty"`

	// LinkedContexts UUIDs of context entries to link. Null clears all linked contexts.
	LinkedContexts *[]openapi_types.UUID `json:"linked_contexts,omitempty"`

	// Series Series name. Null clears the series assignment.
	Series *string `json:"series,omitempty"`

	// Title Updated document title. Null clears the title.
	Title *string `json:"title,omitempty"`
}

// PatchJobBody Mutable job fields. Only present fields are applied.
type PatchJobBody struct {
	// Options Per-job configuration options.
	Options *JobOptions `json:"options,omitempty"`
}

// PatchRunBody Fields to update on an existing run. Typically used to record user answers to clarification questions.
type PatchRunBody struct {
	// Questions Questions with updated `answer` values.
	Questions *[]RunQuestion `json:"questions,omitempty"`

	// Suggestions LLM-proposed updates to document and linked context.
	Suggestions *RunSuggestions `json:"suggestions,omitempty"`
}

// Pipeline Pipeline configuration with stage summaries.
type Pipeline struct {
	// Id Pipeline identifier (filename stem).
	Id string `json:"id"`

	// Name Human-readable pipeline name.
	Name string `json:"name"`

	// Stages Ordered list of stage summaries.
	Stages []StageSummary `json:"stages"`
}

// PipelineDetail Full pipeline configuration with stage details.
type PipelineDetail struct {
	// Id Pipeline identifier (filename stem).
	Id string `json:"id"`

	// Name Human-readable pipeline name.
	Name string `json:"name"`

	// Stages Ordered list of stage details.
	Stages []StageDetail `json:"stages"`
}

// PutJobStatusBody Desired job status. Only valid transitions are accepted.
type PutJobStatusBody struct {
	// Status Target status. `running` and `waiting` are system-only and cannot be set by clients.
	Status PutJobStatusBodyStatus `json:"status"`
}

// PutJobStatusBodyStatus Target status. `running` and `waiting` are system-only and cannot be set by clients.
type PutJobStatusBodyStatus string

// RagRetrieval RAG retrieval configuration for a chat.
type RagRetrieval struct {
	// Enabled Whether RAG retrieval is enabled for this chat.
	Enabled *bool `json:"enabled,omitempty"`

	// MaxSources Maximum number of source documents to retrieve per query.
	MaxSources *int `json:"max_sources,omitempty"`

	// MinimumScore Minimum similarity score for retrieved sources.
	MinimumScore *float32 `json:"minimum_score,omitempty"`
}

// Run A single LLM round trip within a job execution. Jobs accumulate runs over their
// lifetime — each execution (initial run, retry, or re-run after clarification)
// appends a new run to the list.
type Run struct {
	// Confidence LLM-reported confidence in the output.
	Confidence RunConfidence `json:"confidence"`

	// CreatedAt ISO 8601 timestamp when this run started.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique run identifier.
	Id openapi_types.UUID `json:"id"`

	// Inputs Fields fed into the LLM.
	Inputs []RunIOField `json:"inputs"`

	// Outputs Fields produced by the LLM.
	Outputs []RunIOField `json:"outputs"`

	// Questions Clarification questions raised by the LLM.
	Questions []RunQuestion `json:"questions"`

	// Suggestions LLM-proposed updates to document and linked context.
	Suggestions RunSuggestions `json:"suggestions"`

	// UpdatedAt ISO 8601 timestamp when this run was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// RunConfidence LLM-reported confidence in the output.
type RunConfidence string

// RunIOField A single input or output field for an LLM run.
type RunIOField struct {
	// Field Field name (e.g. `ocr_raw`, `clarified_text`).
	Field *string `json:"field"`

	// Text Field value.
	Text string `json:"text"`
}

// RunQuestion A clarification question raised by the LLM, with optional answer.
type RunQuestion struct {
	// Answer The user's answer. Null until answered.
	Answer *string `json:"answer,omitempty"`

	// Question The clarification question to present to the user.
	Question string `json:"question"`

	// Segment The text segment that prompted the question.
	Segment string `json:"segment"`
}

// RunSuggestions LLM-proposed updates to document and linked context.
type RunSuggestions struct {
	// AdditionalContext Suggested update to the document's additional context.
	AdditionalContext *string `json:"additional_context,omitempty"`

	// LinkedContext Suggested update to the linked context entry text.
	LinkedContext *string `json:"linked_context,omitempty"`

	// LinkedContextId UUID of the linked context entry this suggestion applies to.
	LinkedContextId *openapi_types.UUID `json:"linked_context_id,omitempty"`
}

// SendMessageBody A new user message to send to the chat.
type SendMessageBody struct {
	// Content The user's message text.
	Content string `json:"content"`
}

// SourceDoc A document or series corpus chunk retrieved from the vector store as a RAG source.
type SourceDoc struct {
	// DateMonth YYYY-MM month label for the document.
	DateMonth *string `json:"date_month,omitempty"`

	// DocumentId UUID of the source document. Null for series corpus chunks.
	DocumentId *openapi_types.UUID `json:"document_id,omitempty"`

	// Score Vector similarity score.
	Score float32 `json:"score"`

	// SeriesName Series name for corpus chunks that span multiple documents.
	SeriesName *string `json:"series_name,omitempty"`

	// Summary Brief summary of the document's content.
	Summary *string `json:"summary,omitempty"`

	// Title Document title.
	Title *string `json:"title,omitempty"`
}

// StageDetail defines model for StageDetail.
type StageDetail struct {
	// ContinueIf Rules that determine if the stage auto-advances without human review.
	ContinueIf *[]map[string]interface{} `json:"continue_if,omitempty"`

	// Inputs Field names consumed by this stage.
	Inputs *[]string `json:"inputs,omitempty"`

	// Model Model used by this stage.
	Model *string `json:"model,omitempty"`

	// Name Stage identifier (e.g. `ocr`, `clarify`).
	Name string `json:"name"`

	// Outputs Fields produced by this stage.
	Outputs *[]struct {
		// Field Output field name.
		Field string `json:"field"`

		// Type Output type (e.g. `text`, `json_array`).
		Type string `json:"type"`
	} `json:"outputs,omitempty"`

	// SkipIf Conditions under which this stage is skipped entirely.
	SkipIf *map[string]interface{} `json:"skip_if,omitempty"`

	// StartIf Conditions that must be met before this stage can start.
	StartIf *map[string]interface{} `json:"start_if,omitempty"`

	// Type Stage handler type (e.g. `llm_text`, `embed`).
	Type string `json:"type"`
}

// StageSummary Lightweight stage representation used in pipeline list views.
type StageSummary struct {
	// Model Model used by this stage.
	Model *string `json:"model,omitempty"`

	// Name Stage identifier (e.g. `ocr`, `clarify`).
	Name string `json:"name"`

	// Type Stage handler type (e.g. `llm_text`, `embed`).
	Type string `json:"type"`
}

// UpdateContextBody Fields to update on a context entry. Omitted fields are unchanged.
type UpdateContextBody struct {
	// Name Updated name. Null leaves unchanged.
	Name *string `json:"name,omitempty"`

	// Text Updated context text. Null leaves unchanged.
	Text *string `json:"text,omitempty"`
}

// ArtifactId defines model for artifact_id.
type ArtifactId = openapi_types.UUID

// ContextId defines model for context_id.
type ContextId = openapi_types.UUID

// DocId defines model for doc_id.
type DocId = openapi_types.UUID

// JobId defines model for job_id.
type JobId = openapi_types.UUID

// PageSize defines model for page_size.
type PageSize = int

// PageToken defines model for page_token.
type PageToken = string

// PipelineId defines model for pipeline_id.
type PipelineId = string

// RunId defines model for run_id.
type RunId = openapi_types.UUID

// SortOrder defines model for sort_order.
type SortOrder string

// StagesFilter defines model for stages_filter.
type StagesFilter = string

// StatusesFilter defines model for statuses_filter.
type StatusesFilter = string

// NotFound Generic error body.
type NotFound = ErrorResponse

// ListChatsParams defines parameters for ListChats.
type ListChatsParams struct {
	// PageSize Maximum number of results to return (default 50, max 1000).
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
	BeforeId *string   `form:"before_id,omitempty" json:"before_id,omitempty"`
}

// ListContextsParams defines parameters for ListContexts.
type ListContextsParams struct {
	// PageToken Opaque cursor token returned by the previous page response. Omit for the first page.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`

	// PageSize Maximum number of results to return (default 50, max 1000).
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ListDocumentsParams defines parameters for ListDocuments.
type ListDocumentsParams struct {
	// PageToken Opaque cursor token returned by the previous page response. Omit for the first page.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`

	// PageSize Maximum number of results to return (default 50, max 1000).
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Sort Sort order.
	Sort *ListDocumentsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Stages Comma-separated list of pipeline stage names to filter by.
	Stages *StagesFilter `form:"stages,omitempty" json:"stages,omitempty"`

	// Statuses Comma-separated list of job statuses to filter by.
	Statuses *StatusesFilter `form:"statuses,omitempty" json:"statuses,omitempty"`
}

// ListDocumentsParamsSort defines parameters for ListDocuments.
type ListDocumentsParamsSort string

// UploadDocumentMultipartBody defines parameters for UploadDocument.
type UploadDocumentMultipartBody struct {
	AdditionalContext *string               `json:"additional_context,omitempty"`
	File              openapi_types.File    `json:"file"`
	LinkedContexts    *[]openapi_types.UUID `json:"linked_contexts,omitempty"`

	// Series Series name for grouping related documents into a shared embedding corpus.
	Series *string `json:"series,omitempty"`
	Title  *string `json:"title,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	// JobId Comma-separated list of job UUIDs for a 1:1 fetch by ID.
	JobId *string `form:"job_id,omitempty" json:"job_id,omitempty"`

	// DocumentId Comma-separated list of document UUIDs to filter jobs by.
	DocumentId *string `form:"document_id,omitempty" json:"document_id,omitempty"`

	// PageToken Opaque cursor token returned by the previous page response. Omit for the first page.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`

	// PageSize Maximum number of results to return (default 50, max 1000).
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Stages Comma-separated list of pipeline stage names to filter by.
	Stages *StagesFilter `form:"stages,omitempty" json:"stages,omitempty"`

	// Statuses Comma-separated list of job statuses to filter by.
	Statuses *StatusesFilter `form:"statuses,omitempty" json:"statuses,omitempty"`

	// Sort Sort order.
	Sort *ListJobsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// ListJobsParamsSort defines parameters for ListJobs.
type ListJobsParamsSort string

// ListPipelinesParams defines parameters for ListPipelines.
type ListPipelinesParams struct {
	// PageToken Opaque cursor token returned by the previous page response. Omit for the first page.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`

	// PageSize Maximum number of results to return (default 50, max 1000).
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ReceiveWebhookMultipartBody defines parameters for ReceiveWebhook.
type ReceiveWebhookMultipartBody struct {
	// Attachment PNG image of the reMarkable sheet.
	Attachment *openapi_types.File `json:"attachment,omitempty"`

	// Data JSON-encoded document metadata from rmfakecloud.
	Data *string `json:"data,omitempty"`
}

// CreateChatJSONRequestBody defines body for CreateChat for application/json ContentType.
type CreateChatJSONRequestBody = CreateChatBody

// PatchChatJSONRequestBody defines body for PatchChat for application/json ContentType.
type PatchChatJSONRequestBody = PatchChatBody

// SendChatMessageJSONRequestBody defines body for SendChatMessage for application/json ContentType.
type SendChatMessageJSONRequestBody = SendMessageBody

// CreateContextJSONRequestBody defines body for CreateContext for application/json ContentType.
type CreateContextJSONRequestBody = CreateContextBody

// UpdateContextJSONRequestBody defines body for UpdateContext for application/json ContentType.
type UpdateContextJSONRequestBody = UpdateContextBody

// UploadDocumentMultipartRequestBody defines body for UploadDocument for multipart/form-data ContentType.
type UploadDocumentMultipartRequestBody UploadDocumentMultipartBody

// PatchDocumentJSONRequestBody defines body for PatchDocument for application/json ContentType.
type PatchDocumentJSONRequestBody = PatchDocumentBody

// PatchJobJSONRequestBody defines body for PatchJob for application/json ContentType.
type PatchJobJSONRequestBody = PatchJobBody

// PatchRunJSONRequestBody defines body for PatchRun for application/json ContentType.
type PatchRunJSONRequestBody = PatchRunBody

// PutJobStatusJSONRequestBody defines body for PutJobStatus for application/json ContentType.
type PutJobStatusJSONRequestBody = PutJobStatusBody

// ReceiveWebhookMultipartRequestBody defines body for ReceiveWebhook for multipart/form-data ContentType.
type ReceiveWebhookMultipartRequestBody ReceiveWebhookMultipartBody
